version: "3.8"

services:

  kong:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      kong-migration:
        condition: service_completed_successfully
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_ADMIN_LISTEN=0.0.0.0:8001

  kong-migration:
    image: kong:3.1.1-alpine
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
    command: kong migrations bootstrap

  orion:
    image: fiware/orion:3.8.0
    depends_on:
      mongo:
        condition: service_healthy
    command: -logLevel "debug" -dbhost "mongo"

  postgres:
    image: postgres:15.1-bullseye
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kongpass
    healthcheck:
      test: pg_isready -U kong || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo:
    image: mongo:4.4
    command: --nojournal
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

