name: "Test"

concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request: {}
  push:
    branches:
    - main
  schedule:
  - cron: '0 0 * * *'  # every day at midnight, to test against nightlies

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        kongVersion:
        - "2.8.x"

    steps:
    - uses: actions/checkout@v3

    - run: git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
    - run: KONG_VERSION=${{ matrix.kongVersion }} ../kong-pongo/pongo.sh up
    - run: KONG_VERSION=${{ matrix.kongVersion }} ../kong-pongo/pongo.sh build
    - run: KONG_VERSION=${{ matrix.kongVersion }} ../kong-pongo/pongo.sh run
    - run: KONG_VERSION=${{ matrix.kongVersion }} ../kong-pongo/pongo.sh down

